repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-ast
      - id: check-byte-order-marker
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-toml
      # - id: check-yaml # Até encontrar como resolver o problema com emojis
      - id: debug-statements
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
      - id: check-added-large-files

-   repo: https://github.com/psf/black
    rev: 24.4.0
    hooks:
      - id: black
        args: ['--line-length=79']
        files: '(\.pyi?|wscript|ipynb)$'
        language_version: python3
        additional_dependencies: [black-nb]
-   repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort
-   repo: https://github.com/asottile/pyupgrade
    rev: v3.15.2
    hooks:
      - id: pyupgrade
        args: [--py36-plus]
-   repo: https://github.com/PyCQA/flake8
    rev: '7.0.0'
    hooks:
      - id: flake8
-   repo: https://github.com/GussSoares/create-requirements
    rev: 'v0.1.0'
    hooks:
      - id: create-requirements
-   repo: https://github.com/compilerla/conventional-pre-commit
    rev: 'v3.2.0'
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
-   repo: local
    hooks:
      - id: copy-notebooks
        name: copy-notebooks
        language: system
        entry: cp
        args: [-r, notebooks/, docs/]
        pass_filenames: false
        require_serial: true
        files: 'notebooks/'
